# Use the Python3.7.2 image
FROM python:3.7.12-buster

# Set the working directory to /app
WORKDIR /plaid-back-end

# Copy the current directory contents into the container at /app 
ADD . /plaid-back-end

# Install the dependencies
RUN pip install -r requirements.txt


# run the command to start uWSGI
EXPOSE 5002 
# ENTRYPOINT [ "python" ] 
# CMD [ "wsgi.py" ]
# docker-entrypoint.sh is requried to 
    # flask db init
    # flask db migrate
    # flask db upgrade
CMD ["/bin/bash", "docker-entrypoint.sh"]